name: Docker-compose remote deploy with action

on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Start Deployment
        run: |
          echo "${{ secrets.SSH_PEM }}" | tr -d '\r' > key.pem
          chmod 400 key.pem
          ssh -i key.pem  -o "StrictHostKeyChecking no" ubuntu@ec2-3-21-171-204.us-east-2.compute.amazonaws.com <<'ENDSSH'
          pwd
          ls
          ENDSSH
