name: Docker-compose remote deploy with action

on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Deployment
        run: |
          echo "${{ secrets.SSH_PEM }}" | tr -d '\r' > key.pem
          chmod 400 key.pem
          scp -i key.pem  -o "StrictHostKeyChecking no" docker-compose.yaml ubuntu@ec2-3-21-171-204.us-east-2.compute.amazonaws.com:/home/ubuntu/
          ssh -i key.pem  -o "StrictHostKeyChecking no" ubuntu@ec2-3-21-171-204.us-east-2.compute.amazonaws.com <<'ENDSSH'
          sudo su ubuntu
          docker-compose up -d
          ENDSSH
